### ISSUE TITLE
Identifying available time stamped variables

### ISSUE THREAD

**Issue by vmoitra** [eth-mds/ricu#6] opened 2021-12-17 14:53 UTC
I came across your paper on the RICU interface to intensive care data.  I am NOT a stastician and most of my work is adminsitrative and as a clinician.  I am, however, interested in exploring research in critical care databases.  I have an account with physio NET.  As a non statistician, if I wanted to figure out what variables had time stamps and what outcomes were available (MMIC, Amsterdam, HRid, Berlin), how can I figure that out?  My hope is to develop a data analysis plan before finding a statistician.

**Comment by nbenn** [comment] 2021-12-17 16:36
In ricu we have, what we call a dictionary of concepts, covering ~100 variables corresponding to vitals, lab tests, medications, etc. Before setting up the full datasets, for some initial exploration, you could restrict yourself to the demo datasets. But all of this can of course be run, using full data as well. First, we load this dictionary for the demo datasets:

```r
dict <- load_dictionary(c("mimic_demo", "eicu_demo"))
length(dict)
#> [1] 119
head(dict)
#> <concept[6]>
#>                                   abx                              adh_rate
#>            antibiotics <lgl_cncpt[4]>       vasopressin rate <num_cncpt[3]>
#>                                   adm                                   age
#> patient admission type <fct_cncpt[2]>            patient age <num_cncpt[2]>
#>                                   alb                                   alp
#>                albumin <num_cncpt[2]>   alkaline phosphatase <num_cncpt[2]>
```

Concept availability is fairly consistent over datasets, but in some cases, does vary due to availability of corresponding raw data. I only show the top 6 concepts using `head()`, but you can easily reproduce this for the full ~100 concept. In order to answer your question pertaining to time-series data, you can query the target type of concepts:

```r
head(concept_availability(dict))
#>          eicu_demo mimic_demo
#> abx           TRUE       TRUE
#> adh_rate      TRUE       TRUE
#> adm           TRUE       TRUE
#> age           TRUE       TRUE
#> alb           TRUE       TRUE
#> alp           TRUE       TRUE
head(explain_dictionary(dict, cols = c("name", "target")))
#>       name target
#> 1      abx ts_tbl
#> 2 adh_rate ts_tbl
#> 3      adm id_tbl
#> 4      age id_tbl
#> 5      alb ts_tbl
#> 6      alp ts_tbl
```

Now, whenever the target type is `ts_tbl`, the concept represents time-varying data. Other target types are `id_tbl` (for static data such as age, admission type, etc.) and `win_tbl` for time-stamped interval data, such as for example certain infusions.

**Comment by dplecko** [comment] 2023-12-29 17:38
To close this, I am attaching the availability of concepts in `ricu 0.6.0`:

```
> concept_availability()
             aumc  eicu eicu_demo hirid  miiv mimic mimic_demo   sic
abx          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
adh_rate     TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
adm          TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE FALSE
age          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
alb          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
alp          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
alt          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
ast          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
basos        TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
be           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
bicar        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
bili         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
bili_dir     TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
bnd          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
bun          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
ca           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
cai          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
ck           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
ckmb         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
cl           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
cort         TRUE FALSE     FALSE  TRUE FALSE FALSE      FALSE FALSE
crea         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
crp          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
dbp          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
death        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
dex          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
dobu_dur     TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
dobu_rate    TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
dopa_dur     TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
dopa_rate    TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
egcs         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
eos          TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
epi_dur      TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
epi_rate     TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
esr          TRUE FALSE     FALSE  TRUE  TRUE  TRUE       TRUE FALSE
etco2        TRUE FALSE     FALSE  TRUE  TRUE  TRUE       TRUE FALSE
ett_gcs      TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
fgn          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
fio2         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
glu          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
hba1c        TRUE FALSE     FALSE FALSE  TRUE  TRUE       TRUE FALSE
hbco         TRUE  TRUE      TRUE  TRUE FALSE FALSE      FALSE FALSE
hct          TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
height       TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
hgb          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
hr           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
inr_pt       TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
ins          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
k            TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
lact         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
los_hosp    FALSE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE FALSE
los_icu      TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
lymph        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
map          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
mch          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
mchc         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
mcv          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
mech_vent    TRUE FALSE     FALSE  TRUE  TRUE FALSE      FALSE FALSE
methb        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
mg           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
mgcs         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
na           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
neut         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
norepi_dur   TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
norepi_rate  TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
o2sat        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
pco2         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
ph           TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
phn_rate    FALSE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE FALSE
phos         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
plt          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
po2          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
pt           TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
ptt          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
rass         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
rbc          TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
rdw          TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
resp         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
samp         TRUE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE FALSE
sbp          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
sex          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
tco2        FALSE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE FALSE
temp         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
tgcs        FALSE  TRUE      TRUE FALSE FALSE  TRUE       TRUE FALSE
tnt          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
tri         FALSE  TRUE      TRUE FALSE  TRUE  TRUE       TRUE  TRUE
urine        TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
vent_end    FALSE  TRUE      TRUE FALSE FALSE  TRUE       TRUE FALSE
vent_start  FALSE  TRUE      TRUE FALSE FALSE  TRUE       TRUE FALSE
vgcs         TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE FALSE
wbc          TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
weight       TRUE  TRUE      TRUE  TRUE  TRUE  TRUE       TRUE  TRUE
```

**Closed by dplecko** 2023-12-29 17:38 UTC
