### ISSUE TITLE
Elixhauser index

### ISSUE THREAD

**Issue by royarkaprava** [eth-mds/ricu#4] opened 2021-10-14 16:02 UTC
Hi,
Is there a way to calculate Elixhauser commorbidity index using ricu package?

-Arkaprava

**Comment by nbenn** [comment] 2021-10-15 11:45
This depends on the kind of data that is provided by the individual datasets. The HiRID dataset, for example, does not contain any diagnosis information, while AUMC does, but it's all in Dutch. On the MIMIC datasets as well as eICU, on the other hand, this should be fairly straightforward, as they contain ICD coded diagnoses which can for example be fed into the [icd package](https://jackwasey.github.io/icd/).

**Comment by prockenschaub** [comment] 2022-04-06 13:00
Just in case someone comes across this, the large proportion of missingness in the MIMIC IV temperature concept is caused by the inclusion of `itemid==224027` in the concept definition, which relates to a skin temperature measurement (rather than body temperature).

```r
load_id(miiv$d_items, itemid == 224027)

> # An `id_tbl`: 1 x 9
> # Id var:      `itemid`
>   itemid label            abbreviation linksto     category          unitname param_type lownormalvalue highnormalvalue
>    <int> <chr>            <chr>        <chr>       <chr>             <chr>    <chr>               <dbl>           <dbl>
> 1 224027 Skin Temperature Skin Temp    chartevents Skin - Assessment NA       Text                   NA              NA
```

The value here isn't a numeric C or F measurement, but is a subjective categorical classification into cool, warm, hot, etc. As you can see below, the numeric value is `NA` and accounts for the high number of missing entries. 

```r
load_ts(miiv$chartevents, itemid == 224027) %>% 
   select(itemid:valueuom) %>% 
   slice(1:5)

>    itemid value valuenum valueuom
> 1: 224027  Warm       NA     <NA>
> 2: 224027  Cool       NA     <NA>
> 3: 224027  Warm       NA     <NA>
> 4: 224027  Warm       NA     <NA>
> 5: 224027  Warm       NA     <NA>

```

@nbenn I would suggest removing `itemid==224027` from the definition. I can write a PR if you want.

**Comment by nbenn** [comment] 2022-04-10 10:50
@prockenschaub sure, go ahead if you like, sounds reasonable. Thanks for investigating! I'll try to get this merged a bit quicker than last time. This would probably also affect the other mimic datasets, i.e. `mimic` and potentially also `mimic_demo` no?

**Comment by prockenschaub** [comment] 2022-04-29 08:58
Created the PR. Sorry that it took so long, didn't do it right away and then forgot...

**Comment by dplecko** [comment] 2023-12-22 16:53
This seems to be resolved, thanks @prockenschaub and @nbenn.

**Closed by dplecko** 2023-12-22 16:53 UTC
